name-template: 'v$RESOLVED_VERSION 🌈'
tag-template: 'v$RESOLVED_VERSION'
template: |
  # What's Changed

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION

categories:
  # 重大变更
  - title: 'Breaking'
    labels:
      - 'breaking'
      - 'breaking change'
      - 'breaking changes'
    # 新功能
  - title: '🚀 New'
    labels:
      - 'feat'
      - 'feature'
      - 'new'
    # bug修复
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
    # 维护
  - title: '🧰 Maintenance'
    labels:
      - 'maintenance'
      - 'maintain'
      - 'maintained'
    # 文档
  - title: 'Documentation'
    labels:
      - 'docs'
      - 'documentation'
      - 'doc'
    # 其他变更
  - title: 'Other changes'
    labels:
      - '*'
    # 依赖更新
  - title: 'Dependency Updates'
    labels:
      - 'dependencies'
      - 'dep'
      - 'depend'
      - 'dependency'
    collapse-after: 5
    # 版本变更
  - title: 'Version Changes'
    labels:
      - 'version'
      - 'version change'
      - 'version changes'
      - 'release'

version-resolver:
  major:
    labels:
      - 'breaking'
  minor:
    labels:
      - 'feature'
  patch:
    labels:
      - 'bug'
      - 'maintenance'
      - 'docs'
      - 'dependencies'
      - 'security'
  default: patch
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'
exclude-labels:
  - 'skip-changelog'

commitish: main

autolabeler:
  - label: 'bug'
    branch:
      - '/fix\/.+/'
  - label: 'docs'
    branch:
      - '/docs\/.+/'
    files:
      - '*.md'
  - label: 'dependencies'
    branch:
      - '/deps\/.+/'
    files:
      - 'pom.xml'
  - label: 'breaking'
    branch:
      - '/breaking\/.+/'
  - label: 'feature'
    branch:
      - '/feat\/.+/'
  - label: 'maintenance'
    branch:
      - '/maintenance\/.+/'
  - label: 'security'
    branch:
      - '/security\/.+/'
  - label: 'skip-changelog'
    branch:
      - '/skip-changelog\/.+/'
